### ISSUE TITLE
PowerBI SQL Information points to dbadatabase hardcoded

### ISSUE THREAD

**Issue by PsPsam** [SQLDBAWithABeard/dbareports#13]
![image](https://cloud.githubusercontent.com/assets/20344934/17927671/0fceadda-69f7-11e6-8bd4-10b8ac9e53aa.png)

**Comment by SQLDBAWithABeard** [comment]
Thank you

Hard coded database names removed with commit f41fa19dd1d946c78d5c1fefe822e765ad3750dc

Rob
