### ISSUE TITLE
Remove 3-part names from SSRS shared datasets

### ISSUE THREAD

**Issue by amtwo** [SQLDBAWithABeard/dbareports#6]
The default db name is "dbareports" but a non-default can be used on install. Reports should avoid using the DB name in the query text.  The Db name will come from the DB specified in the Data Source.

The following datasets include reference to the dbareports database:

- DailyDiskSpace.rsd
- DatabaseLastUsedTotal.rsd
- LogFileErrors.rsd
- LowDiskSpace.rsd
- NoOfDatabasesEnvDom.rsd
- ServerName.rsd
- ServersByOperatingSystem.rsd
- SuspectPages.rsd

**Comment by js0505** [comment]
Fixed on latest push.
