### ISSUE TITLE
Quick View Report Click-thru broken

### ISSUE THREAD

**Issue by amtwo** [SQLDBAWithABeard/dbareports#7]
"Action" on text to linked reports seems to be broken/missing?

- Number disks <10%
-- Go to report: Disk Space
- Number of failed jobs today
-- Go to report: Agent Job Summary

**Comment by js0505** [comment]
Click on the charts and they should bring you to where you need to go, let me know if you want the text to link as well.

**Comment by amtwo** [comment]
Oh--- Clicking the gauge works.... Should the text be clickable, too? Or maybe just clarify the label to "Click on the gauge for more info" 

I guess this is a "usability" thing rather than a real bug.

**Comment by js0505** [comment]
updated to click on text as well
