### ISSUE TITLE
Agent Job Details - layout/formatting

### ISSUE THREAD

**Issue by amtwo** [SQLDBAWithABeard/dbareports#9]
The current red/green conditional highlighting is difficult to read. 
Also, we should avoid red/green color coding to be colorblind friendly.
`=IIF(Fields!Outcome.Value = "Failed", "Red", "Green")`

Instead of conditional formatting of the row, let's split the outcome column into 2 columns: one for the text outcome, and another that includes an icon for the success/failure.  We should use either a red X or a green check. We'll have to find or create icons that are clear, bold, and simple--to fit existing styling, and provide a fast, clear indicator.

![image](https://cloud.githubusercontent.com/assets/9381581/17878258/9cf4a070-68b7-11e6-865d-de7dd76df463.png)

**Comment by amtwo** [comment]
Something like this:

![green-check](https://cloud.githubusercontent.com/assets/9381581/17878547/88d0e44e-68b9-11e6-83cb-1239899d37f2.png)
![red-x](https://cloud.githubusercontent.com/assets/9381581/17878546/88cecb14-68b9-11e6-84a7-74fcbd8201df.gif)

**Comment by js0505** [comment]
Thoughts on just using the built-in indicators?  I am going to work on that.

**Comment by ctrlbold** [comment]
Oh, man. I totally agree on using an indicator instead. The built-in ones are a bit dated looking, though. Can you guys use fonts? If so, would you consider Font Awesome Xs and Checks with Green and Red (or more pleasant versions of green and red that go with your base set from that website) coloring? Or alternatively, use Andy's suggestion?I think it's a good idea to keep the idea of beauty and simplicity as a focus if possible, though i know it can be hard/time consuming.

**Comment by js0505** [comment]
Might have to use Fonts Awesome Xs, if row size expands indicator is horrific looking.

**Comment by amtwo** [comment]
Using fonts presents a problem--they need to be installed on the SSRS Server. And if the user is going to save to a different format (or send the report as email), then everyone handling the exported report needs to have the font installed.  It will be much easier to manage if we stick to core fonts.

**Comment by amtwo** [comment]
I've had good luck with including "icon" type images in the report project, then including the image as a reference.... Then if we decide we want to change the "x" image at some point in the future, we just need to update the one image and re-deploy.

**Comment by SQLDBAWithABeard** [comment]
Agreed - Enabling access to colour blind people is good practice and using icon representation will also assist with that and improve the look of the report. The aim always is to make it friendly and enticing for managers as well as useful and easy to see the issues for DBAs. As a side note please keep the sorting so that failed jobs migrate to the top of the list

**Comment by SQLDBAWithABeard** [comment]
Quick test for slack

**Comment by js0505** [comment]
Sorting stayed the same, and everything I have done so far has been committed/pushed to the dev branch.

**Comment by js0505** [comment]
Can we close this issue?
